name: main

on:
  push:
    branches:
      - "main"

jobs:
  eslint:
    name: Integrate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        width:
          build: npm run build
          start: npm start
          browser: chrome
