name: main

on: pull_request

jobs:
  eslint:
    name: Integrate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev
          browser: chrome
          headed: true
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
